wallet/src/main/scala/org/alephium/wallet/service/WalletService.scala
wallet/src/test/scala/org/alephium/wallet/service/WalletServiceSpec.scala

The bug was that we were calling the `checkIsMiner` function when
listing the wallets while it's not needed and this function requires the wallets to be
unlocked.
In the fix we reduce the usage of the `checkIsMiner` function only to
the ones that really needed to know if they have a miner wallet or not.
Fix #128

Fix `listWallets` that was returning a `WalletLocked`

---

app/src/it/scala/org/alephium/app/ShutdownTest.scala
flow/src/main/resources/system_it.conf.tmpl
flow/src/main/resources/system_test.conf.tmpl

The it test is flaky as the retry timeout is too big, so the node does
not know if its peer is down

Fix shutdown test

---

flow/src/main/resources/system_it.conf.tmpl
flow/src/main/scala/org/alephium/flow/network/broker/BrokerHandler.scala

The 1 second ping frequency can make integration test flaky when
pong message cannot arrive in 1 second. 5 seconds should be fine.
Note that the default value is 300 seconds in production.
Bitcoin uses this value if I recall it correctly.

Increase ping frequency for integration tests

---

api/src/main/scala/org/alephium/api/Endpoints.scala
app/src/main/scala/org/alephium/app/RestServer.scala
app/src/test/scala/org/alephium/app/RestServerSpec.scala

It seems there's a bug in tapir v0.17 where the custom validation
doesn't work from an `EndpointIO.Pair`.
This quick fix will be used until we upgrade at `v0.18`

Fix `TimeInterval` validation

---

tools/src/main/scala/org/alephium/tools/WalletGen.scala

Simply moved the WalletGen from the wallet package to the tools one.

Move WalletGen to tools

---

build.sbt
docker/user-testnet.conf

This PR adds user.conf for testnet inside the containers.
It also refactor a little bit the Dockerfile to follow the best practices, mostly: group RUN statement to limit layers, reorder to facilitate caching, prefer COPY over ADD.

Build docker containers for testnet

---

docker/grafana/provisioning/dashboards/alephium-overview.json
flow/src/main/scala/org/alephium/flow/handler/ChainHandler.scala

Fixes #333.
This adds a gauge metric that reports the target hash rate for each chain.
Example data from testnet:

Add target hash rate metric

---

build.sbt

This short PR is building dev containers with java 17, and produce two tags for the same image, the second one with explicit `-jdk17` suffix

Set java 17 for dev images, add explicit tag for this version

---

api/src/main/resources/openapi.json
api/src/main/scala/org/alephium/api/ApiModel.scala
api/src/main/scala/org/alephium/api/Endpoints.scala
api/src/main/scala/org/alephium/api/EndpointsExamples.scala
api/src/main/scala/org/alephium/api/model/VerifySignature.scala
api/src/test/scala/org/alephium/api/ApiModelSpec.scala
app/src/it/scala/org/alephium/app/CliqueFixture.scala
app/src/it/scala/org/alephium/app/MultisigTest.scala
app/src/main/scala/org/alephium/app/Documentation.scala
app/src/main/scala/org/alephium/app/EndpointsLogic.scala
app/src/main/scala/org/alephium/app/RestServer.scala
app/src/main/scala/org/alephium/app/ServerUtils.scala

Used to check if some data is correctly signed.
Based on: https://developer.bitcoin.org/reference/rpc/verifymessage.html

Add `/utils/verify` endpoint

---

flow/src/test/scala/org/alephium/flow/mining/MinerApiControllerSpec.scala

This seems to cause MinerApiControllerSpec failed twice lately

Use newTestActorRef instead of TestActorRef in MinerApiControllerSpec

---

flow/src/main/resources/logback.xml

Introduce the `ALEPHIUM_LOG_LEVEL` environment variable to make console log configurable. 
Console log is what gets picked up by many cloud provider for cloud logging. For example in GCP console logs gets sent to Stackdriver and enabling INFO level in full node roughly costs 60 euros a month.

Make console log level configurable

---

app/src/test/scala/org/alephium/app/ServerUtilsSpec.scala
flow/src/main/scala/org/alephium/flow/core/TxUtils.scala
flow/src/main/scala/org/alephium/flow/core/UtxoUtils.scala
flow/src/test/scala/org/alephium/flow/core/TxUtilsSpec.scala
protocol/src/main/scala/org/alephium/protocol/model/UnsignedTransaction.scala

1. Add more checks when we build transactions, e.g. gas amount and price, token constrains per tx output, input uniqueness, etc
2. For `sweepAll` endpoint, try to generate more outputs if the number of tokens exceed `maxTokenPerUtxo`.

Apply More Constrains on UTXO Endpoints

---

.github/workflows/release.yaml

Migrate from the old github action for release to softprops' release action to simplify asset upload, and include checksums in releases.

Use softprops' release action & add checksum files to releases

---

README.md

It currently needs some permissions enabled (first image), but once @Sakrecoer enables [the setting on our server](https://github.com/badges/shields/issues/1659#issuecomment-384814358), it will look like the second image

Change discord link to display online users

---

app/src/main/scala/org/alephium/app/EndpointsLogic.scala
app/src/main/scala/org/alephium/app/RestServer.scala
http/src/main/scala/org/alephium/http/EndpointSender.scala
wallet/src/main/scala/org/alephium/wallet/WalletApp.scala
wallet/src/main/scala/org/alephium/wallet/web/BlockFlowClient.scala
wallet/src/test/scala/org/alephium/wallet/service/WalletServiceSpec.scala
wallet/src/test/scala/org/alephium/wallet/web/BlockFlowClientSpec.scala

Resolves: #637
sttp backend needs to be closed to properly free up resources.

Convert `EndpointSender` to a stoppable `Service`

---

http/src/main/scala/org/alephium/http/SwaggerUI.scala

very small fix, but necessary so I can use `SwaggerUI` in `explorer-backend`. Without this it redirect to `/docs/openapi.json` while I have define another file name.

Fix swagger ui redirection

---

ralph/src/main/scala/org/alephium/ralph/Ast.scala
ralph/src/test/scala/org/alephium/ralph/AstSpec.scala
ralph/src/test/scala/org/alephium/ralph/CompilerSpec.scala

With the following code
```
@std(id = #0005)
Interface Foo {
pub fn foo() -> ()                                                                                                                                                                                                                    
}
@std(id = #000401)
Interface Bar extends Foo {
pub fn bar() -> ()                                                                                                                                                                                                                    
}
```
The compiler will print `The std id of interface Bar should starts with 414c50480005` instead of `The std id of interface Bar should starts with 0005`

Print Correct Error Message with Wrong Prefixed StdId

---

wallet/src/main/scala/org/alephium/wallet/service/WalletService.scala

Resolves: #959
From the java doc we can read:
```
Unlike the createDirectory method, an exception is not thrown if the directory 
could not be created because it already exists.
```
So it was fine to call the function on every start, but as mentioned in issue #959, it doesn't work with symbolic link because the function throws:
```
FileAlreadyExistsException - if dir exists but is not a directory (optional specific exception)
```
As here it's a link and not a directory, the error raised.
To fix this we can simply first check if the directory/link exists.

Check if wallets secret dir exist before creating it

---

api/src/main/resources/openapi.json
api/src/main/scala/org/alephium/api/TapirCodecs.scala
api/src/main/scala/org/alephium/api/TapirSchemas.scala

While tackling https://github.com/alephium/explorer-backend/issues/484
I realize we can improve our `Codec` to have the format added to our types when they are used in path query.

Add `Schema` to `Codec`

---

api/src/main/resources/openapi.json
api/src/main/scala/org/alephium/api/ApiModel.scala
api/src/main/scala/org/alephium/api/Endpoints.scala
api/src/main/scala/org/alephium/api/EndpointsExamples.scala
api/src/main/scala/org/alephium/api/model/TargetToHashrate.scala
api/src/test/scala/org/alephium/api/ApiModelSpec.scala
app/src/main/scala/org/alephium/app/Documentation.scala
app/src/main/scala/org/alephium/app/EndpointsLogic.scala
app/src/main/scala/org/alephium/app/RestServer.scala
app/src/test/scala/org/alephium/app/RestServerSpec.scala

Target to hashrate endpoint

---

ralph/src/main/scala/org/alephium/ralph/Parser.scala
ralph/src/main/scala/org/alephium/ralph/Type.scala

Currently it only make sense to add a source index to:
- `NamedType`
- `FixedSizeArray` 
Other `Type` aren't constructed at parsing or are case object and having the `var sourceIndex` don't make sense on them.

Add `Ast.Positioned` to `Type`

---

app/src/it/scala/org/alephium/app/InterCliqueSyncTest.scala
flow/src/test/scala/org/alephium/flow/AlephiumFlowSpec.scala
flow/src/test/scala/org/alephium/flow/core/BlockFlowGroupViewSpec.scala
flow/src/test/scala/org/alephium/flow/core/BlockFlowSpec.scala

`BlockFlowGroupViewSpec` sometimes fails in Windows because we sort blocks by timestamp when updating the state: https://github.com/alephium/alephium/blob/56dc17a40bf1f0944d027f529c716fbe137f1d3d/flow/src/main/scala/org/alephium/flow/core/BlockFlowState.scala#L406

Fix flaky tests

---

api/src/main/scala/org/alephium/api/OpenApiWriters.scala
app/src/main/scala/org/alephium/app/RestServer.scala
app/src/test/scala/org/alephium/app/RestServerSpec.scala
tools/src/main/scala/org/alephium/tools/OpenApiUpdate.scala
wallet/src/main/scala/org/alephium/wallet/web/WalletServer.scala

This would render swagger UI on `DevNet` or `TestNet` with functioning addresses so endpoints can be tested. Addresses are truncated only on `MainNet` so that users/devs don't send there their own ALPHs by accident.
Tests are reading truncated `openapi.json` for `MainNet` and they reverse address truncation in order to pass on `DevNet`.
Tested manually by `make assembly` and checking swagger on `DevNet`.

Truncate addresses in openapi on mainnet only

---

ralph/src/main/scala/org/alephium/ralph/Parser.scala
ralph/src/test/scala/org/alephium/ralph/ParserSpec.scala

A default value shouldn't have a source index as it's not written in the code.
I tested it with ralph-lsp as the [source issue came from there](https://github.com/alephium/ralph-lsp/issues/452), it works well.
Resolves https://github.com/alephium/alephium/issues/1262

Fix source index of enum with a default value
