alephium/alephium

api/src/main/resources/openapi.yaml, api/src/main/scala/org/alephium/api/ApiError.scala, api/src/main/scala/org/alephium/api/ApiModel.scala, api/src/main/scala/org/alephium/api/DecodeFailureHandler.scala, api/src/main/scala/org/alephium/api/Endpoints.scala, api/src/main/scala/org/alephium/api/EndpointsExamples.scala, api/src/test/scala/org/alephium/api/ApiErrorSpec.scala, app/src/main/scala/org/alephium/app/RestServer.scala, app/src/main/scala/org/alephium/app/ServerUtils.scala, app/src/test/scala/org/alephium/app/RestServerSpec.scala, project/scalastyle-config.xml, util/src/test/scala/org/alephium/util/SocketUtil.scala, wallet/src/main/scala/org/alephium/wallet/api/WalletEndpoints.scala, wallet/src/main/scala/org/alephium/wallet/api/WalletExamples.scala, wallet/src/main/scala/org/alephium/wallet/api/model/WalletDeletion.scala, wallet/src/main/scala/org/alephium/wallet/circe/ModelCodecs.scala, wallet/src/main/scala/org/alephium/wallet/service/WalletService.scala, wallet/src/main/scala/org/alephium/wallet/storage/SecretStorage.scala, wallet/src/main/scala/org/alephium/wallet/web/AkkaDecodeFailureHandler.scala, wallet/src/main/scala/org/alephium/wallet/web/BlockFlowClient.scala, wallet/src/main/scala/org/alephium/wallet/web/WalletServer.scala, wallet/src/test/scala/org/alephium/wallet/WalletAppSpec.scala, wallet/src/test/scala/org/alephium/wallet/service/WalletServiceSpec.scala, wallet/src/test/scala/org/alephium/wallet/storage/SecretStorageSpec.scala
two features in one enpdpoint.
This PR resolves  #130 by adding a `detail` field. The api errors are also unified across the all project.
This is a first step for a better error handling, currently the errors aren't very rich, but the skeleton is there to add more info latter, the goal is to follow a bit https://tools.ietf.org/html/rfc7807
=> Improve error handling and add an endpoint to delete wallet

docker/Dockerfile, docker/README.md, docker/docker-compose.yml, docker/user-testnet.conf
This MR provides a simple dockerization of Alephium, so that anyone with docker installed can easily run Alephium.
=> [docker] Simple dockerization to build and run Alephium as container

api/src/main/resources/openapi.json, app/src/it/scala/org/alephium/app/BlocksExportImportTest.scala, app/src/it/scala/org/alephium/app/BroadcastTxTest.scala, app/src/it/scala/org/alephium/app/InterCliqueSyncTest.scala, app/src/it/scala/org/alephium/app/IntraCliqueSyncTest.scala, app/src/it/scala/org/alephium/app/MiningTest.scala, app/src/it/scala/org/alephium/app/ShutdownTest.scala, app/src/it/scala/org/alephium/app/SmartContractTest.scala, app/src/it/scala/org/alephium/app/TestFixture.scala, app/src/main/scala/org/alephium/app/Documentation.scala, app/src/test/scala/org/alephium/app/WebSocketServerSpec.scala, docker/README.md, flow/src/test/scala/org/alephium/flow/network/BootstrapperSpec.scala, flow/src/test/scala/org/alephium/flow/network/DiscoveryServerSpec.scala, flow/src/test/scala/org/alephium/flow/network/broker/BrokerHandlerSpec.scala, flow/src/test/scala/org/alephium/flow/setting/AlephiumConfigFixture.scala, flow/src/test/scala/org/alephium/flow/setting/AlephiumConfigSpec.scala, http/src/test/scala/org/alephium/http/HttpFixture.scala, make, project/scalastyle-config.xml, project/scalastyle-test-config.xml, serde/src/test/scala/org/alephium/serde/SerdeSpec.scala, util/src/test/scala/org/alephium/util/SocketUtil.scala, wallet/src/main/resources/application.conf, wallet/src/main/scala/org/alephium/wallet/WalletApp.scala, wallet/src/test/scala/org/alephium/wallet/WalletAppSpec.scala, wallet/src/test/scala/org/alephium/wallet/config/WalletConfigFixture.scala, wallet/src/test/scala/org/alephium/wallet/web/BlockFlowClientSpec.scala
This reverts commit ab5d5a366eeef896b1bbb5933a552ff181b09284.
It seems it introduced flakyness in CI
=> Revert "Randomize ports in `AlephiumConfigFixture`"

api/src/main/resources/openapi.json, api/src/main/scala/org/alephium/api/ApiModel.scala, api/src/main/scala/org/alephium/api/Endpoints.scala, api/src/main/scala/org/alephium/api/EndpointsExamples.scala, api/src/main/scala/org/alephium/api/model/NodeInfo.scala, api/src/test/scala/org/alephium/api/ApiModelSpec.scala, app/src/main/scala/org/alephium/app/Documentation.scala, app/src/main/scala/org/alephium/app/RestServer.scala, app/src/test/scala/org/alephium/app/RestServerSpec.scala, flow/src/main/scala/org/alephium/flow/client/Miner.scala, flow/src/test/scala/org/alephium/flow/client/MinerSpec.scala
=> Add `/infos/node` endpoint

util/src/main/scala/org/alephium/util/Duration.scala, util/src/test/scala/org/alephium/util/DurationSpec.scala
Add more tests for the `Duration` class
=> Test duration

api/src/main/resources/openapi.json, api/src/main/scala/org/alephium/api/ApiModel.scala, api/src/main/scala/org/alephium/api/EndpointsExamples.scala, api/src/main/scala/org/alephium/api/model/NodeInfo.scala, api/src/test/scala/org/alephium/api/ApiModelSpec.scala, app/src/main/scala/org/alephium/app/EndpointsLogic.scala, app/src/test/scala/org/alephium/app/RestServerSpec.scala, protocol/src/main/scala/org/alephium/protocol/model/ReleaseVersion.scala, protocol/src/test/scala/org/alephium/protocol/model/ReleaseVersionSpec.scala, wallet/src/main/scala/org/alephium/wallet/api/WalletExamples.scala, wallet/src/main/scala/org/alephium/wallet/api/model/AddressInfo.scala, wallet/src/main/scala/org/alephium/wallet/api/model/Addresses.scala, wallet/src/main/scala/org/alephium/wallet/json/ModelCodecs.scala, wallet/src/main/scala/org/alephium/wallet/web/WalletEndpointsLogic.scala, wallet/src/test/scala/org/alephium/wallet/WalletAppSpec.scala, wallet/src/test/scala/org/alephium/wallet/json/ModelCodecsSpec.scala
* Node version in `/infos/node`
* Add group info in wallet's address info
=> Improve endpoints info

api/src/main/resources/openapi.json, api/src/main/scala/org/alephium/api/EndpointsExamples.scala, api/src/main/scala/org/alephium/api/model/BuildContract.scala, api/src/main/scala/org/alephium/api/model/BuildMultisig.scala, api/src/main/scala/org/alephium/api/model/BuildScript.scala, api/src/main/scala/org/alephium/api/model/BuildSweepAllTransaction.scala, api/src/main/scala/org/alephium/api/model/BuildTransaction.scala, api/src/main/scala/org/alephium/api/model/UtxoBasedModel.scala, api/src/test/scala/org/alephium/api/ApiModelSpec.scala, app/src/main/scala/org/alephium/app/ApiConfig.scala, app/src/main/scala/org/alephium/app/ServerUtils.scala, app/src/test/scala/org/alephium/app/RestServerSpec.scala, app/src/test/scala/org/alephium/app/ServerFixture.scala, app/src/test/scala/org/alephium/app/ServerUtilsSpec.scala, flow/src/main/resources/system_it.conf.tmpl, flow/src/main/resources/system_prod.conf.tmpl, flow/src/main/resources/system_test.conf.tmpl, flow/src/main/scala/org/alephium/flow/core/TxUtils.scala, flow/src/main/scala/org/alephium/flow/core/package.scala, flow/src/test/scala/org/alephium/flow/AlephiumFlowSpec.scala, flow/src/test/scala/org/alephium/flow/core/BlockFlowSpec.scala, flow/src/test/scala/org/alephium/flow/core/TxUtilsSpec.scala, flow/src/test/scala/org/alephium/flow/validation/TxValidationSpec.scala, wallet/src/main/scala/org/alephium/wallet/api/model/SweepAll.scala, wallet/src/main/scala/org/alephium/wallet/api/model/Transfer.scala, wallet/src/main/scala/org/alephium/wallet/service/WalletService.scala, wallet/src/main/scala/org/alephium/wallet/web/BlockFlowClient.scala, wallet/src/main/scala/org/alephium/wallet/web/WalletEndpointsLogic.scala, wallet/src/test/scala/org/alephium/wallet/service/WalletServiceSpec.scala
The goal of this PR is to make utxo limit configurable for all utxo based endpoints.
@Lbqds @liuhongchao @tdroxler (alphabetical order) please help me review this PR
=> Fix utxo limit

api/src/main/resources/openapi.json, api/src/main/scala/org/alephium/api/Examples.scala, wallet/src/main/scala/org/alephium/wallet/api/WalletExamples.scala
=> Improve wallet api examples

api/src/main/resources/openapi.json, api/src/main/scala/org/alephium/api/model/Compile.scala, app/src/it/scala/org/alephium/app/CliqueFixture.scala, app/src/it/scala/org/alephium/app/VotingTest.scala
Add integration test for a voting smart contract example.
=> Voting demo

api/src/main/resources/openapi.json, api/src/main/scala/org/alephium/api/EndpointsExamples.scala, api/src/main/scala/org/alephium/api/model/BuildTransactionResult.scala, api/src/test/scala/org/alephium/api/ApiModelSpec.scala, wallet/src/test/scala/org/alephium/wallet/WalletAppSpec.scala
Add gas information as required in issue #500
=> Add gas amount and gas price in BuildTransactionResult

api/src/main/resources/openapi.json, api/src/main/scala/org/alephium/api/EndpointsExamples.scala, api/src/main/scala/org/alephium/api/model/SweepAddressTransaction.scala, api/src/test/scala/org/alephium/api/ApiModelSpec.scala, wallet/src/main/scala/org/alephium/wallet/service/WalletService.scala
=> Add `gasAmount` and `gasPrice` to `SweepAddressTransaction`

app/src/main/scala/org/alephium/app/CpuSoloMiner.scala, app/src/main/scala/org/alephium/app/Server.scala, flow/src/main/scala/org/alephium/flow/core/BlockHeaderChain.scala, flow/src/main/scala/org/alephium/flow/mining/CpuMiner.scala, flow/src/main/scala/org/alephium/flow/mining/ExternalMinerMock.scala, flow/src/main/scala/org/alephium/flow/mining/MinerApiController.scala, flow/src/test/scala/org/alephium/flow/mining/MinerSpec.scala
* Use mining dispatcher for mining connections actors
* Refactor a bit
=> Improve mining dispatcher

flow/src/test/scala/org/alephium/flow/core/VMSpec.scala, protocol/src/main/scala/org/alephium/protocol/vm/lang/Ast.scala, protocol/src/main/scala/org/alephium/protocol/vm/lang/Compiler.scala, protocol/src/main/scala/org/alephium/protocol/vm/lang/Lexer.scala, protocol/src/main/scala/org/alephium/protocol/vm/lang/Parser.scala, protocol/src/test/scala/org/alephium/protocol/vm/lang/CompilerSpec.scala, protocol/src/test/scala/org/alephium/protocol/vm/lang/ParserSpec.scala
Add `Abstract TxContract`, example
```
TxContract Child(mut x: U256) extends Parent0(x), Parent1(x) {                                                                                                                                        
pub fn foo() -> () {                                                                                                                                                                                
p0()                                                                                                                                                                                              
p1() …
```
=> Introduce Abstract TxContract

crypto/src/test/scala/org/alephium/crypto/AESSpec.scala, flow/src/test/scala/org/alephium/flow/AlephiumFlowSpec.scala, flow/src/test/scala/org/alephium/flow/core/VMSpec.scala, protocol/src/main/scala/org/alephium/protocol/vm/Context.scala, protocol/src/main/scala/org/alephium/protocol/vm/Frame.scala, protocol/src/main/scala/org/alephium/protocol/vm/Instr.scala, protocol/src/main/scala/org/alephium/protocol/vm/lang/BuiltIn.scala, protocol/src/test/scala/org/alephium/protocol/vm/InstrSpec.scala, protocol/src/test/scala/org/alephium/protocol/vm/lang/BuiltInSpec.scala
Add optional address argument for 
- `createContractWithToken`
- `copyCreateContractWithToken`
- `createSubContractWithToken`
- `copyCreateSubContractWithToken`
which will receive the created token
=> Create Contract and Transfer Token

docker/docker-compose.yml
=> limit logs file size

ralph/src/main/scala/org/alephium/ralph/Ast.scala, ralph/src/main/scala/org/alephium/ralph/Parser.scala, ralph/src/test/scala/org/alephium/ralph/CompilerSpec.scala
Resolves https://github.com/alephium/ralph-lsp/issues/152
=> Add position to `Inheritance`

ralphc/src/main/scala/org/alephium/ralphc/Compiler.scala
Resolves https://github.com/alephium/ralph-lsp/issues/245.
=> Close resource

app/src/main/scala/org/alephium/app/ApiConfig.scala, app/src/main/scala/org/alephium/app/RestServer.scala, app/src/test/scala/org/alephium/app/ApiConfigSpec.scala, app/src/test/scala/org/alephium/app/RestServerSpec.scala, app/src/test/scala/org/alephium/app/ServerUtilsSpec.scala, flow/src/main/resources/system_it.conf.tmpl, flow/src/main/resources/system_prod.conf.tmpl, flow/src/main/resources/system_test.conf.tmpl
=> Introduce `max-form-buffered-kilo-byte` config value

.github/workflows/styling.yml, .jvmopts, build.sbt, project/Boilerplate.scala, serde/src/main/scala/org/alephium/serde/ProductSerde.scala, serde/src/main/scala/org/alephium/serde/ProductSerializer.scala, serde/src/test/scala/org/alephium/serde/ProductSerdeSpec.scala
To get around the following issue of Metals, so we could live happily with Cursor editor.
Ref issue: https://github.com/scalameta/metals/pull/7006
=> Remove automatic codegen

flow/src/main/resources/system_prod.conf.tmpl
A [request](https://discord.com/channels/747741246667227157/948144672402972682/1372942397113368667) from discord.
=> Add ALEPHIUM_API_KEY_ENABLED variable
